// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shzcowvtiettumquygug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoemNvd3Z0aWV0dHVtcXV5Z3VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5OTY4MjAsImV4cCI6MjA2MDU3MjgyMH0.cZUnT4nYKoET33lepq14bdyn-IkJinhqnLnLQrh1UfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});